spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_assignment4?useUnicode=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    generate-ddl: true
  server:
    port: 8080

